name: Build read-it-and-keep images

on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - main
      - gh_actions_test
  pull_request:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    name: Build linux/singularity
    runs-on: ubuntu-20.04
    steps:

    - name: Set up Go 1.16
      uses: actions/setup-go@v1
      with:
        go-version: 1.16
      id: go

    - name: Install Dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y \
          build-essential \
          libssl-dev \
          uuid-dev \
          libgpgme11-dev \
          squashfs-tools \
          libseccomp-dev \
          pkg-config \
          debootstrap \
          debian-keyring \
          debian-archive-keyring \
          rsync

    - name: Install Singularity
      env:
        SINGULARITY_VERSION: 3.5.3
        GOPATH: /tmp/go
      run: |
        mkdir -p $GOPATH
        sudo mkdir -p /usr/local/var/singularity/mnt
        mkdir -p $GOPATH/src/github.com/sylabs
        cd $GOPATH/src/github.com/sylabs
        wget https://github.com/hpcng/singularity/releases/download/v${SINGULARITY_VERSION}/singularity-${SINGULARITY_VERSION}.tar.gz
        tar -xzf singularity-${SINGULARITY_VERSION}.tar.gz
        cd singularity
        ./mconfig -v -p /usr/local
        make -j `nproc 2>/dev/null || echo 1` -C ./builddir all
        sudo make -C ./builddir install


    - name: Check out code for the container build
      uses: actions/checkout@v2

    - name: Set release version if is a release
      if: startsWith(github.event.ref, 'refs/tags/v')
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Set release version if not a release
      if: false == startsWith(github.event.ref, 'refs/tags/v')
      run: echo "RELEASE_VERSION=test" >> $GITHUB_ENV

    - name: Build Singularity container
      env:
        SINGULARITY_RECIPE: Singularity.def
        OUTPUT_CONTAINER: readItAndKeep_${{env.RELEASE_VERSION}}.img
      run: |
        ls
        if [ -f "${SINGULARITY_RECIPE}" ]; then
            sudo -E singularity build ${OUTPUT_CONTAINER} ${SINGULARITY_RECIPE}
        else
            echo "${SINGULARITY_RECIPE} is not found."
            echo "Present working directory: $PWD"
            ls
        fi

    - name: Release
      if: startsWith(github.event.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      with:
        files: readItAndKeep*.img
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Log in to github container registry
      if: startsWith(github.event.ref, 'refs/tags/v')
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      if: startsWith(github.event.ref, 'refs/tags/v')
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    - name: Build and push Docker image
      if: startsWith(github.event.ref, 'refs/tags/v')
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}


  mac_build:
    name: Build mac os
    runs-on: macos-11
    steps:

    - name: Check out code for the build
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        pip3 install pytest pyfastaq
        wget -q https://ftp.gnu.org/gnu/gsl/gsl-2.7.1.tar.gz
        tar xf gsl-2.7.1.tar.gz
        rm gsl-2.7.1.tar.gz
        cd gsl-2.7.1
        ./configure
        make
        make install
        cd ..

        wget -q https://www.niehs.nih.gov/research/resources/assets/docs/artsrcmountrainier2016.06.05macos.tgz
        tar xf artsrcmountrainier2016.06.05macos.tgz
        rm artsrcmountrainier2016.06.05macos.tgz
        cd art_src_MountRainier_MacOS
        export CFLAGS="$CFLAGS -I/usr/local/include" CPPFLAGS="$CPPFLAGS -I/usr/local/include" LDFLAGS="$LDFLAGS -L/usr/local/lib"
        ./configure
        make
        cd ..
        pwd
        ls -lh /Library/Frameworks/Python.framework/Versions/3.12/include/python3.12
        ls -lh /Library/Frameworks/Python.framework/Versions/3.12/include/python3.12/cpython
        mkdir test_lib
        cp /Library/Frameworks/Python.framework/Versions/3.12/include/python3.12/cpython/longintrepr.h test_lib/
        export CFLAGS="$CFLAGS -I$PWD/test_lib"
        export CPPFLAGS="$CPPFLAGS -I$PWD/test_lib"
        #export CFLAGS="$CFLAGS -I/Library/Frameworks/Python.framework/Versions/3.12/include/python3.12"
        #export CPPFLAGS="$CPPFLAGS -I/Library/Frameworks/Python.framework/Versions/3.12/include/python3.12"

        wget -q https://github.com/rrwick/Badread/archive/refs/tags/v0.2.0.tar.gz
        tar xf v0.2.0.tar.gz
        rm v0.2.0.tar.gz
        cd Badread-0.2.0
        pip3 install .

    - name: Build and run tests
      run: |
          export PATH=$PWD/art_src_MountRainier_MacOS:$PATH
          cd src
          make
          make test

